global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "3.148.113.160:9093"
rule_files:
  - alertrules.yml

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "3.148.113.160:9100"
